# Generated by Django 4.0.1 on 2022-01-08 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_income_delete_expense'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ['-date']},
        ),
    ]
